#'Returns the inverse of matrix. if cached then return the cached inverse.
#'
#'@param x - datastructure generated by makeCacheMatrix
#'@author Priyesh Kannan
#'@description This function computes the inverse of the special "matrix" returned by makeCacheMatrix.
#'If the inverse has already been calculated (and the matrix has not changed),
#'then the cachesolve should retrieve the inverse from the cache.
#'@seealso \code{\link{solve}} Used to find inverse of a matrix
#'@seealso \code{\link{makeCacheMatrix}} Create necessary data structure for cacheSolve function
#'@export cacheSolve
#'@usage
#' mat_data<-makeCacheMatrix(matrix(rnorm(9),3,3))
#' inverse<-cacheSolve(mat_data)
#'
#'
cacheSolve <-
function(x, ...) {
  ## Return a matrix that is the inverse of 'x'
  inverse <- x$getInverse()
  if( !is.null(inverse)){
    message("getting cached data")
    return(inverse)
  }
  data <- x$get()
  inverse <- solve(data,...)
  x$setInverse(inverse)
  inverse
}
